apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: p-nov-28
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      approvers:
      - userName: ravi@rafay.co
      timeout: 2m0s
      type: Email
    name: approv
    type: Approval
  triggers:
  - config:
      repo:
        paths:
        - name: demo
        provider: Github
        repository: nov-28
        revision: main
    name: custom-webhook-trigger
    type: Webhook
