apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: p-dec-27-projects-inside-1x
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      approvers:
      - userName: ravi@rafay.co
      timeout: 2m20s
      type: Email
    name: approv
    type: Approval
