apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: p-skipped-4
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      destinationRepo:
        path:
          name: dec27
        repository: dec19
        revision: main
      includedResources:
      - name: Pipeline
      - name: Catalog
      - name: Addon
      - name: Workload
      systemToGitSync: true
    name: s
    type: SystemSync
  triggers:
  - config:
      repo:
        paths:
        - name: dec16
        provider: Github
        repository: nov-28
        revision: main
    name: hook
    type: Webhook
  - config:
      repo:
        paths:
        - name: hook
        provider: Github
        repository: dec19
        revision: main
    name: dec19repohook
    type: Webhook
  - config:
      repo:
        paths:
        - name: hook
        provider: Github
        repository: dec27
        revision: main
    name: dec27repohook
    type: Webhook
