apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: cat-addon-1-0-3
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: catalog-custom-2
      chartName: cron-chart
      chartVersion: 1.0.3
      valuesPaths:
      - name: file://cat-addon-1-0-3/Values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: ns-for-catalog
  sharing: {}
  version: v1.0.3
