apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-d-2
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: l-d-2
  resourceQuotas: {}
