apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-dec-12
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: i-1
  resourceQuotas: {}
