apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-del-2
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: c-1
  resourceQuotas: {}
