apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-g-2
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: g-5
  resourceQuotas: {}
