apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: wl-gitops-dec22
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://deployment.yaml
    options: {}
    type: Yaml
  namespace: ns-dec22
  placement:
    selector: rafay.dev/clusterName=import-dec22-1x
  version: v1
