apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: wl-gitops-dec23-1x
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://deployment.yaml
    options: {}
    type: Yaml
  namespace: ns-dec23-gitops
  placement:
    selector: rafay.dev/clusterName=ravi-v2-eks-dec23-1x
  version: v1
